### ISSUE TITLE
Exercise 8 and 9 should be swapped

### ISSUE THREAD

**Issue by sdcubber** [tdpetrou/pandas_cub#1]
Exercise 8 involves the uncommenting of the `_repr_html_` method. However, this method invokes the `self._values` attribute, which is only implemented in excercise 9. Hence, completing exercise 8 and trying it out in the notebook results in a `AttributeError: 'DataFrame' object has no attribute '_values'`. This would be solved by swapping both exercises.

**Comment by tdpetrou** [comment]
Thanks for checking this assignment. This is a bug. It needs to be `_data`. I changed the name of the private variable but forgot to change it in that method. I'll update soon.

**Comment by tdpetrou** [comment]
This is now fixed. Thanks for the report! I changed a few more things so you'll probably want to use the latest version.
