### ISSUE TITLE
diff is not tested with negative numbers

### ISSUE THREAD

**Issue by gtcooke94** [tdpetrou/pandas_cub#2]
First of all just wanted to say I think this is a really cool project you've put together, thanks for doing it!

I ran across this issue because I messed up the diff method when I first wrote it, but my tests passed because the test_diff test only tests a shift of 1. It seems like a good idea to test a negative index to get more complete coverage.

On the other hand, I don't know if you are interested in adding more tests to this or not, because that opens a box of lots of potential edge cases to add.

If you're interested in people adding tests I'd be happy to open a PR if that's the route you want to take.

**Comment by tdpetrou** [comment]
Thanks very much for the feedback and thanks for proceeding through the project. Yes, the tests are definitely lacking coverage in some areas, even though there are nearly 100 of them. I think your point about opening up a pandora's box of edge cases is on point. I think the tests are good enough at the moment to accomplish the goals of the project.

I think I can add something to the readme about adding coverage to the tests as something worthwhile to do on your own once all the steps have finished.

**Comment by gtcooke94** [comment]
Sounds good - I'll close this issue.
