### ISSUE TITLE
_unicode_to_object test case issue

### ISSUE THREAD

**Issue by najafmurtaza** [tdpetrou/pandas_cub#3]
In test case _unicode_to_object,  assert_array_equal doesn't verify the datatypes of arrays.
This code still passes the test case.

```
def _convert_unicode_to_object(self, data):
	converted_data = {}
	for key, val in data.items():
		if val.dtype.kind == 'U':
			converted_data[key] = data[key]
		else:
			converted_data[key] = data[key]

	return converted_data
```

**Update:**
This verifies the type conversion correctly.
```
def test_unicode_to_object(self):
        a_object = a.astype('O')
        assert df._data['a'].dtype.kind == a_object.dtype.kind
        assert df._data['b'].dtype.kind == b.dtype.kind
        assert df._data['c'].dtype.kind == c.dtype.kind
        assert df._data['d'].dtype.kind == d.dtype.kind
        assert df._data['e'].dtype.kind == e.dtype.kind
```

**Comment by tdpetrou** [comment]
Yes, it appears that there is no data type checking. Could probably add to the testing function, but I don't see much benefit in adding it to the project. I would advise you to add it to your version of the project though. Thank you for reporting this, but I don't want the code to veer off much, or at all, of how it is presented in the course.
